version: "3.9"
services:
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile.prod
    ports:
      - 80:80
    env_file:
      - prod.env
    healthcheck:
      test: curl --fail http://localhost:80 || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
  backend:
    build:
      context: backend
      dockerfile: Dockerfile.prod
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
      mq:
        condition: service_healthy
    env_file:
      - prod.env
    healthcheck:
      test: curl --fail http://localhost:8000 || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
  db:
    image: postgres:15
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - prod.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: always
  mq:
    image: rabbitmq:3.11
    volumes:
      - './data/mq:/var/lib/rabbitmq/mnesia/'
    ports:
      - '5672:5672'
      - '15672:15672'
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 5s
      retries: 10